---
# Main tasks for computers role
- name: Create Active Directory computer accounts
  ansible.builtin.import_tasks: create.yml

- name: Verify Active Directory computer accounts
  ansible.builtin.import_tasks: verify.yml

...
