---
# Main tasks for groups role
- name: Create Active Directory OUs
  ansible.builtin.import_tasks: create_ous.yml

- name: Verify Active Directory OUs
  ansible.builtin.import_tasks: verify.yml

...  

# - include_tasks: create.yml
# - include_tasks: memberships.yml
# - include_tasks: verify.yml
